### PR TITLE
Code cleaning, fixes, and CI

### PR DESCRIPTION
**Pull request by Vermeille**

### CODE REVIEW

**Comment by roby65** [comment]
That's a huge work for a single man!
I can't believe someone has still so much interest in this game to invest so much time. Thank you!
Unfortunately I am the one responsible for the DirectDraw bridge. Shame on me. I was so crazy to think that it would be easier, the code got a lot more complicated. But at least it worked.
Let me take a look and I will merge those changes.

Thank you!

**Comment by Vermeille** [comment]
I'm actually super thankful that you built that bridge. It's a smart way to get the game to work on Linux without impacting the rest of the code.

You got the work done with a tractable amount of work. This bridge is actually a smart decision to get the work done.

Thanks you, because I wouldn't have contributed to the game if I had to write code on Windows :)

And yes, this game is so much of my childhood, I was delighted to see that I could bring it back <3

**Comment by roby65** [comment]
I am a little curious about a thing.
Did you change how the player selection works?
I can't remember exactly now, but I am pretty sure it wasn't done the proper way and it was the most intensive scene in the game.

**Comment by Vermeille** [comment]
Oh God yeah I remember I could not go after the character selection screen with gdb because it's just running full speed with no fps cap and it took forever. 

To be fair, I don't remember if I changed something there, but I might have. I also have changed some synchronous input polling into asynchronous waits, like for the pause and title menus (hooray FSMs!).

**Comment by Vermeille** [comment]
Tbh I'm first cleaning low level stuff so that the code is easier to work with before going after the much needed algorithmic and architectural changes

**Comment by Vermeille** [comment]
Btw I'm in no way a game developer so I don't know the common patterns, but if you do know what a better architecture would be to get rid of all those globals (a Singleton is not better) without introducing a god object, I'm all ears. I've started thinking about a pub/sub system maybe.

It's not doable now as the code needs a lot of disentanglement / de-spaghetti-fying, but it's good starting to think about it

**Comment by roby65** [comment]
Let me think about that, a lot of time has passed. But the pub/sub sounds good.
I will check your pull request today/tomorrow and merge it tomorrow max.
A lot of time has passed from when I worked here, my main objectives were:
- Adding linux support
- Optimizing/refactoring the code that needs it
- Adding online multiplayer
I stopped after linux support, it was a massive work for one person only.
Online multiplayer may be impossible, I have to think about that.
If you think you may continue contributing, I would love to get my hand deep in here again and contribute too. I would love that.

About the player selection screen, I will check it out again, I am sure there is something wrong going on. Someone compiled the game for Android (unfortunately it is no on the Play Store anymore) and that screen is the only one lagging on my old device.

**Comment by Vermeille** [comment]
Oh, well, don't expect any consistent work from me on that. I just put a bit of time on Blip&Blop whenever I need a break from my thesis or I feel rusty on my C++ :)

Refactoring code is uh, my way of relaxing (and I needed a lot of zen few months ago haha). Feeling obliged or feeling some kind of pressure because someone else is expecting some work from me is definitely the last thing I want from Blip & Blop lol.

I can take a look at the character selection screen again during the WE, maybe.

My own set of "goals" are more focused about internals rather than features:

* cleaner and more modern code
* better code architecture wrt to levels / game engine
* better code architecture wrt to sprites / characters / objects
* unifying all those game loops
* unlocking the game from this now ridiculous resolution
* greater extensibility through Lua or something like that rather than C++ for anything that's not core engine
* and well, I'd love a python API to have it as a reinforcement learning platform, for instance

It might take years as I know I can't work on it consistently :)

**Comment by roby65** [comment]
Don't worry, didn't want to put any pressure, just wanted to know what you wanted to do.
Consistency is my problem too, so I feel you.
I like your road map. The "Lua" scripting sounds good!
I will try helping with refactoring too next weeks.
Thanks for you work!

**Pull request merged**
